In [520]:
import numpy as np
from keras import Sequential, losses
from keras.layers import SimpleRNN, Dense, Input, Activation


In [521]:
# Nodes 
# 3

# Timestamps 4
# because -  movie was not good, (len 4)

# len 5
# because of total vocal - 5 (movie, was, not, good, bad)


In [522]:
model = Sequential()

In [523]:
model.add(Input(shape=(4,5)))
model.add(SimpleRNN(3))

In [524]:
model.add(Dense(1))

In [525]:
model.summary()

Model: "sequential_46"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn_45 (SimpleRNN)       │ (None, 3)              │            27 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_41 (Dense)                │ (None, 1)              │             4 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 31 (124.00 B)

 Trainable params: 31 (124.00 B)

 Non-trainable params: 0 (0.00 B)

In [526]:
for index, item in enumerate(model.get_weights()):
    print(item)
    print(item.shape)
    
    print(index)
    print()

[[ 0.10419506 -0.47308752  0.850594  ]
 [ 0.7484327  -0.5396818   0.15350336]
 [-0.20598203 -0.30337518  0.14061028]
 [-0.42383212 -0.3275059   0.51103693]
 [-0.25718886 -0.8560596  -0.08875763]]
(5, 3)
0

[[ 0.5951154  -0.7735589   0.21781707]
 [ 0.8030303   0.58296216 -0.1236832 ]
 [ 0.03130286 -0.2485195  -0.96812093]]
(3, 3)
1

[0. 0. 0.]
(3,)
2

[[0.24384356]
 [0.6286571 ]
 [0.6570934 ]]
(3, 1)
3

[0.]
(1,)
4



In [527]:
model.layers

[<SimpleRNN name=simple_rnn_45, built=True>, <Dense name=dense_41, built=True>]

In [528]:
sentences = np.array([
    "I love machine learning",
    "I love deep learning",
    "Python is very useful",
    "I hate bad code",
    "This movie is amazing",
    "This movie is terrible",
    "I enjoy learning Python",
    "Machine learning is interesting",
    "Deep learning is powerful",
    "I like artificial intelligence",
    "Python programming is easy",
    "The weather is beautiful",
    "I love this movie",
    "The food is delicious",
    "This book is excellent",
    "I dislike this product",
    "The service was terrible",
    "This game is very fun",
    "I enjoy playing games",
    "The course is very helpful",
    "Learning RNN is interesting",
    "Natural language processing is useful",
    "I love programming",
    "Coding is sometimes difficult",
    "This software is amazing",
    "The application is very slow",
    "I am happy today",
    "I am feeling sad",
    "The computer works perfectly",
    "The internet connection is bad"
])

In [529]:
# word toninzer

# play with it


# make sequence

# pad sequence



# aside

# pull imdb review data

# train, test splits 

# play with it.

# prepare for learning

# work on model


In [530]:
from keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.preprocessing.text import Tokenizer

In [531]:
help(Tokenizer)

Help on class Tokenizer in module keras.src.legacy.preprocessing.text:

class Tokenizer(builtins.object)
 |  Tokenizer(num_words=None, filters='!"#$%&()*+,-./:;<=>?@[\\]^_`{|}~\t\n', lower=True, split=' ', char_level=False, oov_token=None, analyzer=None, **kwargs)
 |
 |  DEPRECATED.
 |
 |  Methods defined here:
 |
 |  __init__(self, num_words=None, filters='!"#$%&()*+,-./:;<=>?@[\\]^_`{|}~\t\n', lower=True, split=' ', char_level=False, oov_token=None, analyzer=None, **kwargs)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |
 |  fit_on_sequences(self, sequences)
 |
 |  fit_on_texts(self, texts)
 |
 |  get_config(self)
 |
 |  sequences_to_matrix(self, sequences, mode='binary')
 |
 |  sequences_to_texts(self, sequences)
 |
 |  sequences_to_texts_generator(self, sequences)
 |
 |  texts_to_matrix(self, texts, mode='binary')
 |
 |  texts_to_sequences(self, texts)
 |
 |  texts_to_sequences_generator(self, texts)
 |
 |  to_json(self, **kwargs)
 |
 |  ------------------

In [532]:
toknenizer = Tokenizer(oov_token='<skippit>')

In [533]:
toknenizer.fit_on_texts(sentences)

In [534]:
toknenizer.document_count

30

In [535]:
toknenizer.get_config()

{'num_words': None,
 'filters': '!"#$%&()*+,-./:;<=>?@[\\]^_`{|}~\t\n',
 'lower': True,
 'split': ' ',
 'char_level': False,
 'oov_token': '<skippit>',
 'document_count': 30,
 'word_counts': '{"i": 11, "love": 4, "machine": 2, "learning": 6, "deep": 2, "python": 3, "is": 17, "very": 4, "useful": 2, "hate": 1, "bad": 2, "code": 1, "this": 7, "movie": 3, "amazing": 2, "terrible": 2, "enjoy": 2, "interesting": 2, "powerful": 1, "like": 1, "artificial": 1, "intelligence": 1, "programming": 2, "easy": 1, "the": 7, "weather": 1, "beautiful": 1, "food": 1, "delicious": 1, "book": 1, "excellent": 1, "dislike": 1, "product": 1, "service": 1, "was": 1, "game": 1, "fun": 1, "playing": 1, "games": 1, "course": 1, "helpful": 1, "rnn": 1, "natural": 1, "language": 1, "processing": 1, "coding": 1, "sometimes": 1, "difficult": 1, "software": 1, "application": 1, "slow": 1, "am": 2, "happy": 1, "today": 1, "feeling": 1, "sad": 1, "computer": 1, "works": 1, "perfectly": 1, "internet": 1, "connection": 1

In [536]:
sequences = toknenizer.texts_to_sequences(sentences)

In [537]:
sequences = pad_sequences(sequences,padding='post' )

In [538]:
sequences=sequences.astype(dtype='float32')

In [539]:
input_shape =len(sequences[0]),len(sequences)

In [540]:
labels = np.array([
    1, 1, 1, 0, 1, 0,
    1, 1, 1, 1, 1, 1,
    1, 1, 1, 0, 0, 1,
    1, 1, 1, 1, 1, 1,
    1, 1, 0, 1, 0, 0
], 'float32')

In [541]:
input_shape

(5, 30)

In [542]:
model = Sequential()

model.add(Input(shape=(5,1)))
model.add(SimpleRNN(32))
model.add(Dense(1))

In [543]:
model.add(Activation(activation='sigmoid'))

In [544]:
model.compile(loss=losses.binary_crossentropy, metrics=['accuracy'], optimizer='RMSProp')

In [545]:
X = sequences.reshape(30, 5, 1)
Y= labels


In [546]:
model.summary()

Model: "sequential_47"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn_46 (SimpleRNN)       │ (None, 32)             │         1,088 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_42 (Dense)                │ (None, 1)              │            33 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ activation_11 (Activation)      │ (None, 1)              │             0 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,121 (4.38 KB)

 Trainable params: 1,121 (4.38 KB)

 Non-trainable params: 0 (0.00 B)

In [547]:
model.fit(X, Y, epochs=5)

Epoch 1/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 477ms/step - accuracy: 0.3667 - loss: 0.6998
Epoch 2/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.7667 - loss: 0.6189
Epoch 3/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.7667 - loss: 0.5898
Epoch 4/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.7667 - loss: 0.5743
Epoch 5/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.7667 - loss: 0.5645
